//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_final_Simulación.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"n,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,>50
0.1,0.95,0.77639,0.63604,0.56522,0.50945,0.46799,0.43607,0.40962,0.38746,0.36866,0.35242,0.33815,0.32549,0.31417,0.30397,0.29472,0.28627,0.27851,0.27136,0.26473,0.25858,0.25283,0.24746,0.24242,0.23768,0.2332,0.22898,0.22497,0.22117,0.21756,0.21412,0.21085,0.20771,0.21472,0.20185,0.1991,0.19646,0.19392,0.19148,0.18913,0.18687,0.18468,0.18257,0.18051,0.17856,0.17665,0.17481,0.17301,0.17128,0.16959,1.22
0.05,0.975,0.84189,0.7076,0.62394,0.56328,0.51926,0.48342,0.45427,0.43001,0.40925,0.39122,0.37543,0.36143,0.3489,0.3375,0.32733,0.31796,0.30936,0.30143,0.29408,0.28724,0.28087,0.2749,0.26931,0.26404,0.25908,0.25438,0.24993,0.24571,0.2417,0.23788,0.23424,0.23076,0.22743,0.22425,0.22119,0.21826,0.21544,0.21273,0.21012,0.2076,0.20517,0.20283,0.20056,0.19837,0.19625,0.1942,0.19221,0.19028,0.18841,1.36
8,0.975,0.84189,0.7076,0.62394,0.56328,0.51926,0.48342,0.45427,0.43001,0.40925,0.39122,0.37543,0.36143,0.3489,0.3375,0.32733,0.31796,0.30936,0.30143,0.29408,0.28724,0.28087,0.2749,0.26931,0.26404,0.25908,0.25438,0.24993,0.24571,0.2417,0.23788,0.23424,0.23076,0.22743,0.22425,0.22119,0.21826,0.21544,0.21273,0.21012,0.2076,0.20517,0.20283,0.20056,0.19837,0.19625,0.1942,0.19221,0.19028,0.18841,1.36

")]
        public string TablaKS {
            get {
                return ((string)(this["TablaKS"]));
            }
            set {
                this["TablaKS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"n,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,>50
0.1,0.95,0.77639,0.63604,0.56522,0.50945,0.46799,0.43607,0.40962,0.38746,0.36866,0.35242,0.33815,0.32549,0.31417,0.30397,0.29472,0.28627,0.27851,0.27136,0.26473,0.25858,0.25283,0.24746,0.24242,0.23768,0.2332,0.22898,0.22497,0.22117,0.21756,0.21412,0.21085,0.20771,0.21472,0.20185,0.1991,0.19646,0.19392,0.19148,0.18913,0.18687,0.18468,0.18257,0.18051,0.17856,0.17665,0.17481,0.17301,0.17128,0.16959,1.22
0.05,0.975,0.84189,0.7076,0.62394,0.56328,0.51926,0.48342,0.45427,0.43001,0.40925,0.39122,0.37543,0.36143,0.3489,0.3375,0.32733,0.31796,0.30936,0.30143,0.29408,0.28724,0.28087,0.2749,0.26931,0.26404,0.25908,0.25438,0.24993,0.24571,0.2417,0.23788,0.23424,0.23076,0.22743,0.22425,0.22119,0.21826,0.21544,0.21273,0.21012,0.2076,0.20517,0.20283,0.20056,0.19837,0.19625,0.1942,0.19221,0.19028,0.18841,1.36")]
        public string TablaKSDefault {
            get {
                return ((string)(this["TablaKSDefault"]));
            }
            set {
                this["TablaKSDefault"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"n,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30
0.05,3.841,5.991,7.815,9.488,11.071,12.592,14.067,15.507,16.919,18.307,19.675,21.026,22.362,23.685,24.996,26.296,27.587,28.869,30.144,31.17,32.671,33.924,35.172,36.415,37.652,38.885,40.113,41.337,42.557,43.773
")]
        public string TablaChi {
            get {
                return ((string)(this["TablaChi"]));
            }
            set {
                this["TablaChi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"n,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30
0.05,3.841,5.991,7.815,9.488,11.071,12.592,14.067,15.507,16.919,18.307,19.675,21.026,22.362,23.685,24.996,26.296,27.587,28.869,30.144,31.17,32.671,33.924,35.172,36.415,37.652,38.885,40.113,41.337,42.557,43.773
")]
        public string TablaChiDefault {
            get {
                return ((string)(this["TablaChiDefault"]));
            }
            set {
                this["TablaChiDefault"] = value;
            }
        }
    }
}
